### ISSUE TITLE
dummystore: throws error when cannot find prevLinkHash filter

### ISSUE THREAD

**Issue by jeremie-stratumn** [stratumn/sdk#288]
### Expected behavior
When using a  *non-empty* dummystore, query for a segment using prevLinkHash filter should return an empty list when the prevLinkHash cannot be found

### Actual behavior
/segments?prevLinkHash=<hash> throws the following error:
```
store_1  | 2017/12/11 16:49:01 http: panic serving 172.29.0.1:57428: runtime error: invalid memory address or nil pointer dereference
store_1  | goroutine 78 [running]:
store_1  | net/http.(*conn).serve.func1(0xc420166f00)
store_1  | 	/usr/local/opt/go/libexec/src/net/http/server.go:1697 +0xd0
store_1  | panic(0x6b1760, 0x899650)
store_1  | 	/usr/local/opt/go/libexec/src/runtime/panic.go:491 +0x283
store_1  | github.com/stratumn/sdk/dummystore.(*DummyStore).findHashesSegments(0xc4200683c0, 0xc420199140, 0xc42004cde0, 0x40, 0xc4200fae08, 0x664f3e, 0x6e2320, 0xc42004cde0)
store_1  | 	src/github.com/stratumn/sdk/dummystore/dummystore.go:268 +0x3c3
store_1  | github.com/stratumn/sdk/dummystore.(*DummyStore).FindSegments(0xc4200683c0, 0xc42004cde0, 0x0, 0x0, 0x0, 0x0, 0x0)
store_1  | 	src/github.com/stratumn/sdk/dummystore/dummystore.go:188 +0x1cc
store_1  | github.com/stratumn/sdk/store/storehttp.(*Server).findSegments(0xc42005ae10, 0x86f5c0, 0xc4201210a0, 0xc420123500, 0x0, 0x0, 0x0, 0x2, 0x4803dd, 0xc420048580, ...)
store_1  | 	src/github.com/stratumn/sdk/store/storehttp/storehttp.go:278 +0x59
store_1  | github.com/stratumn/sdk/store/storehttp.(*Server).(github.com/stratumn/sdk/store/storehttp.findSegments)-fm(0x86f5c0, 0xc4201210a0, 0xc420123500, 0x0, 0x0, 0x0, 0x0, 0xc42003fbf8, 0x426301, 0x651c85)
store_1  | 	src/github.com/stratumn/sdk/store/storehttp/storehttp.go:145 +0x73
store_1  | github.com/stratumn/sdk/jsonhttp.handler.ServeHTTP(0xc420068410, 0xc420058ce0, 0x86f5c0, 0xc4201210a0, 0xc420123500, 0x0, 0x0, 0x0)
store_1  | 	src/github.com/stratumn/sdk/jsonhttp/jsonhttp.go:165 +0x7b
store_1  | github.com/stratumn/sdk/jsonhttp.(handler).ServeHTTP-fm(0x86f5c0, 0xc4201210a0, 0xc420123500, 0x0, 0x0, 0x0)
store_1  | 	src/github.com/stratumn/sdk/jsonhttp/jsonhttp.go:105 +0x75
store_1  | github.com/stratumn/sdk/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc42005ae40, 0x86f5c0, 0xc4201210a0, 0xc420123500)
store_1  | 	src/github.com/stratumn/sdk/vendor/github.com/julienschmidt/httprouter/router.go:299 +0x6f1
store_1  | net/http.serverHandler.ServeHTTP(0xc420074dd0, 0x86f5c0, 0xc4201210a0, 0xc420123500)
store_1  | 	/usr/local/opt/go/libexec/src/net/http/server.go:2619 +0xb4
store_1  | net/http.(*conn).serve(0xc420166f00, 0x86fac0, 0xc420049640)
store_1  | 	/usr/local/opt/go/libexec/src/net/http/server.go:1801 +0x71d
store_1  | created by net/http.(*Server).Serve
store_1  | 	/usr/local/opt/go/libexec/src/net/http/server.go:2720 +0x288
```

### Steps to reproduce the behavior

  1. create a new dummyStore and add a segment
  2. then `curl http://localhost:5000/segments?prevLinkHash=a68259b412a426c099e7aa8ff8d64cf5fc0fcd4dcfe7ca77adf21909832465ba`

**Comment by jeremie-stratumn** [comment]
Issue seems gone with new store interface changes. The problem occurred here:
https://github.com/stratumn/sdk/blob/814de2ba61232cf8f17b726079d19e8758ddcb5a/dummystore/dummystore.go#L268
When the segment is an init segment, prevLinkHash is nil and therefore it throws a nil pointer dereference

With new store interface: https://github.com/stratumn/sdk/blob/2f71fbdb57a0e7f54bc5286f4a25a0fe300677ef/store/store.go#L213
We always check if prevLinkHash is nil, if so return false.
